---

#
# This file is part of the Shared Build Config.
#
# (c) Scribe Inc. <oss@scr.be>
#
# For the full copyright and license information, please view the LICENSE.md
# file that was distributed with this source code.
#

scribe_teavee_object_cache :
    enabled : true
    generator :
        prefix : 'teavee-object-cache-bundle-test'
    attendant :
        memcached :
            options_list :
                serializer : serializer_php
            servers_list :
                default :
                    host   : 127.0.0.1
                    port   : 11211
                    weight : 0

...
