---

#
# This file is part of the Shared Build Config.
#
# (c) Scribe Inc. <oss@scr.be>
#
# For the full copyright and license information, please view the LICENSE.md
# file that was distributed with this source code.
#

doctrine :
    dbal :
        connections :
            default :
                driver   : %database_driver%
                host     : %database_host%
                port     : %database_port%
                dbname   : %database_name%
                user     : %database_user%
                password : %database_password%
                charset  : utf8mb4
    orm:
        auto_generate_proxy_classes : true
        proxy_namespace             : Proxies
        proxy_dir                   : %kernel.cache_dir%/doctrine/orm/Proxies
        default_entity_manager      : default

...
