---

#
# This file is part of the Shared Build Config.
#
# (c) Scribe Inc. <oss@scr.be>
#
# For the full copyright and license information, please view the LICENSE.md
# file that was distributed with this source code.
#

framework:
    secret         : "not-so-secret-for-test-config"
    router         : { resource: "%kernel.root_dir%/config/routing.yml" }
    session        : ~
    default_locale : en
    translator     : { fallback: en }
    profiler       : { only_exceptions: false }

...
