---

#
# This file is part of the Shared Build Config.
#
# (c) Scribe Inc. <oss@scr.be>
#
# For the full copyright and license information, please view the LICENSE.md
# file that was distributed with this source code.
#

framework :
    templating :
        engines :
            - "twig"

...
